...@classes

# % FileModule.FileQueryController %
FileModule.FileQueryController -> FileModule.FileQueryService: {
  class: combine
}
FileModule.FileQueryController -> FileModule.FileDownloadService: {
  class: combine
}

# %% FileModule.FileQueryService %%
FileModule.FileQueryService -> FileModule.FilesDAO: {
  class: combine
}
FileModule.FilesDAO -> DBModule.DBClient: {
  class: combine
}
FileModule.FilesDAO -> DBModule.DBSchema: {
  class: combine
}
FileModule.FilesDAO -> IdModule.IdService: {
  class: combine
}

# %% FileModule.FileDownloadService %%
FileModule.FileDownloadService -> FileModule.FilesDAO: {
  class: combine
}
FileModule.FileDownloadService -> S3Module.S3Service: {
  class: combine
}
S3Module.S3Service -> IdModule.IdService: {
  class: combine
}

# % FileModule.FileDeleteController %
FileModule.FileDeleteController -> FileModule.FileDeleteService: {
  class: combine
}

# %% FileModule.FileDeleteService %%
FileModule.FileDeleteService -> FileModule.FilesDAO: {
  class: combine
}
FileModule.FileDeleteService -> S3Module.S3Service: {
  class: combine
}

# % FileModule.FileUploadController %
FileModule.FileUploadController -> FileModule.FileStreamUploadService: {
  class: combine
}
FileModule.FileUploadController -> FileModule.FileMultipartUploadService: {
  class: combine
}
FileModule.FileUploadController -> FileModule.FileCreateVariantService: {
  class: combine
}

# %% FileModule.FileStreamUploadService %%
FileModule.FileStreamUploadService -> FileModule.FilesDAO: {
  class: combine
}
FileModule.FileStreamUploadService -> S3Module.S3Service: {
  class: combine
}

# %% FileModule.FileMultipartUploadService %%
FileModule.FileMultipartUploadService -> FileModule.FilesDAO: {
  class: combine
}
FileModule.FileMultipartUploadService -> S3Module.S3Service: {
  class: combine
}
FileModule.FileMultipartUploadService -> FileModule.MultipartUploadDAO: {
  class: combine
}
FileModule.MultipartUploadDAO -> CacheModule.Cache: {
  class: combine
}

# %% FileModule.FileCreateVariantService %%
FileModule.FileCreateVariantService -> FileModule.FilesDAO: {
  class: combine
}
FileModule.FileCreateVariantService -> S3Module.S3Service: {
  class: combine
}

# % other %
IdModule.IdService -> ConfigModule.Config: {
  class: combine
}
DBModule.DBClient -> ConfigModule.Config: {
  class: combine
}
S3Module.S3Service -> ConfigModule.Config: {
  class: combine
}
CacheModule.Cache -> ConfigModule.Config: {
  class: combine
}
