basic function: {
  explanation: |md
    - upload file
    - multipart upload file
    - download file
    - delete file
  |
}

advanced function: {
  explanation: |md
    - set expiration time
    - create variant
    - file type limit
    - resumable download
    - integrity check
    - download permission
    - delete permission
    - deduplication
    - request variant and fallback to the origin
  |
}

performance requirement: {
  explanation: |md
    - support high concurrency
    - low memory usage
  |
}

other function: {
  explanation: |md
    - handle failure
    - log
    - monitor
    - api document
    - api version management
  |
}

exception: {
  explanation: |md
    - too many chunks
    - slow network
    - low memory
  |
}
