[package]
name = "snowflake-id"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"

[dependencies]
sonyflake = "0.3.0"
wasm-bindgen = "0.2.95"
